curl 'https://duckduckgo.com/html/' -H 'authority: duckduckgo.com' -H 'cache-control: max-age=0' -H 'origin: https://duckduckgo.com' -H 'upgrade-insecure-requests: 1' -H 'content-type: application/x-www-form-urlencoded' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'referer: https://duckduckgo.com/' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.9,es;q=0.8,ca;q=0.7,fr;q=0.6' --data 'q=recetas+melones&b=&kl=us-en' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.hogarmania.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.receta-postres.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.directoalpaladar.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/recetasmelones.blogspot.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/fogonesymelones.blogspot.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/cookpad.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.recetas-saludables.com.ico' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.9,es;q=0.8,ca;q=0.7,fr;q=0.6' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'accept: image/webp,image/apng,image/*,*/*;q=0.8' -H 'referer: https://duckduckgo.com/' -H 'authority: icons.duckduckgo.com' -H 'if-none-match: "5aeb345b-5c6"' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/gastronomiaycia.republica.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.recetas.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/cocina.facilisimo.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/recetasconmelon.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.gallinablanca.es.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.facebook.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.youtube.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.sabervivirtv.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.recetas.page.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/www.petitchef.es.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/elgourmet.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/elcomidista.elpais.com.ico' --compressed ;
curl 'https://icons.duckduckgo.com/ip2/cocina-casera.com.ico' --compressed ;
curl 'https://duckduckgo.com/t/sl_h' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.9,es;q=0.8,ca;q=0.7,fr;q=0.6' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'accept: image/webp,image/apng,image/*,*/*;q=0.8' -H 'referer: https://duckduckgo.com/' -H 'authority: duckduckgo.com' --compressed ;
curl 'https://duckduckgo.com/daily/?h' --compressed ;
curl 'https://duckduckgo.com/weekly/?h' --compressed ;
curl 'https://duckduckgo.com/monthly/?h' --compressed ;
curl 'https://duckduckgo.com/font/ProximaNova-Sbold-webfont.woff' --compressed ;
curl 'https://duckduckgo.com/font/ProximaNova-Reg-webfont.woff' --compressed ;
curl 'https://duckduckgo.com/assets/loupe_gray.png' --compressed ;
curl 'https://duckduckgo.com/assets/logo_header.v107.min.png' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.9,es;q=0.8,ca;q=0.7,fr;q=0.6' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'accept: image/webp,image/apng,image/*,*/*;q=0.8' -H 'referer: https://duckduckgo.com/' -H 'authority: duckduckgo.com' --compressed
